class ExceptionEx5 {
	
	public static int[] makeArray(int length) {
		int[] arr = null;
		try {
			// 실행 보장X
			arr = new int[length];
		} catch(NullPointerException e) {
			// 실행 보장X
			e.printStackTrace();
		} finally {
			// 실행 보장	
			System.out.println("done");
		}
		
		return arr;
	}

	public static void main(String[] args)	{
		makeArray(3);
		makeArray(-3);
		System.out.println("end of main");
	}
}
